package eu.europa.ec.itb.xml.standalone;

import java.io.File;

/**
 * Captures the provided input and the input file name. The file name may be one
 * generated by the validator in case the input is not provided from the file system.
 */
public class ValidationInput {

    private final File inputFile;
    private final String fileName;

    /**
     * Constructor.
     *
     * @param inputFile The input file.
     * @param fileName The file name.
     */
    public ValidationInput(File inputFile, String fileName) {
        this.inputFile = inputFile;
        this.fileName = fileName;
    }

    /**
     * @return The input file.
     */
    public File getInputFile() {
        return inputFile;
    }

    /**
     * @return The file name.
     */
    public String getFileName() {
        return fileName;
    }
}
